// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD284Cjaic_QXN59NnL-_3neKcNXvjxPdA',
    appId: '1:426576214763:web:9e318c6ebd509d38b79cae',
    messagingSenderId: '426576214763',
    projectId: 'chat-app-787a5',
    authDomain: 'chat-app-787a5.firebaseapp.com',
    storageBucket: 'chat-app-787a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFIR6kpjexCvpUeuxoXBCfE7ZgwsgjHAM',
    appId: '1:426576214763:android:0d0a083e5d92c8d7b79cae',
    messagingSenderId: '426576214763',
    projectId: 'chat-app-787a5',
    storageBucket: 'chat-app-787a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlmupPa89cXaD10LCXWAoNAPofy_r0qMI',
    appId: '1:426576214763:ios:c9c783ce5d58cca3b79cae',
    messagingSenderId: '426576214763',
    projectId: 'chat-app-787a5',
    storageBucket: 'chat-app-787a5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlmupPa89cXaD10LCXWAoNAPofy_r0qMI',
    appId: '1:426576214763:ios:0f44a59ed822061fb79cae',
    messagingSenderId: '426576214763',
    projectId: 'chat-app-787a5',
    storageBucket: 'chat-app-787a5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
